"""Payment Detail Migration

Revision ID: efed7520259f
Revises: 65ff6e5df8c9
Create Date: 2021-06-20 18:18:15.265012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efed7520259f'
down_revision = '65ff6e5df8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentdetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debit_card', sa.Integer(), nullable=True),
    sa.Column('bank', sa.String(length=50), nullable=True),
    sa.Column('billing_address', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('friends', 'accepter',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('friends', 'requester',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friends', 'requester',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('friends', 'accepter',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('paymentdetails')
    # ### end Alembic commands ###
