"""empty message

Revision ID: 635dadef4f15
Revises: 3aa5fc46f4c6
Create Date: 2021-06-21 17:16:09.245065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635dadef4f15'
down_revision = '3aa5fc46f4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True, decimal_return_scale=2),
               existing_nullable=False)
    op.alter_column('users', 'balance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, decimal_return_scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=sa.Float(precision=10, decimal_return_scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('transactions', 'cost',
               existing_type=sa.Float(precision=10, asdecimal=True, decimal_return_scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
