"""Friends migration

Revision ID: 65ff6e5df8c9
Revises: 220173591dfc
Create Date: 2021-06-20 18:12:58.097038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ff6e5df8c9'
down_revision = '220173591dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester', sa.Integer(), nullable=True),
    sa.Column('accepter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepter'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
