"""Initial migration.

Revision ID: 220173591dfc
Revises: 
Create Date: 2021-06-20 18:01:55.770650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220173591dfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phonenumber', sa.Integer(), nullable=True),
    sa.Column('profileImage', sa.String(length=256), nullable=True),
    sa.Column('balance', sa.Float(precision=10, asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
